<?php

declare(strict_types = 1);

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function oe_link_list_link_list_access(EntityInterface $entity, $operation, AccountInterface $account) {
  $type = $entity->bundle();
  $access = AccessResult::neutral();

  switch ($operation) {
    case 'create':
      $access = AccessResult::allowedIfHasPermission($account, 'create ' . $type . ' link list');
      break;

    case 'update':
      $access = AccessResult::allowedIfHasPermission($account, 'edit any ' . $type . ' link list');
      if (!$access->isAllowed() && $account->hasPermission('edit own ' . $type . ' link list')) {
        $access = $access->orIf(AccessResult::allowedIf($account->id() == $entity->getOwnerId())->cachePerUser()->addCacheableDependency($entity));
      }
      break;

    case 'delete':
      $access = AccessResult::allowedIfHasPermission($account, 'delete any ' . $type . ' link list');
      if (!$access->isAllowed() && $account->hasPermission('delete own ' . $type . ' link list')) {
        $access = $access->orIf(AccessResult::allowedIf($account->id() == $entity->getOwnerId()))->cachePerUser()->addCacheableDependency($entity);
      }
      break;
  }

  return $access;
}
