<?php

/**
 * @file
 * OpenEuropa Dynamic Link Lists module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for the dynamic link lists add form.
 */
function oe_link_lists_dynamic_form_link_list_dynamic_link_list_add_form_alter(array &$form, FormStateInterface $form_state) {
  oe_link_lists_dynamic_apply_link_list_form_alterations($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter() for the dynamic link lists edit form.
 */
function oe_link_lists_dynamic_form_link_list_dynamic_link_list_edit_form_alter(array &$form, FormStateInterface $form_state) {
  oe_link_lists_dynamic_apply_link_list_form_alterations($form, $form_state);
}

/**
 * Alters the dynamic link list ADD and EDIT forms.
 *
 * Adds the form elements for selecting and configuring the plugin to use, as
 * well as the submit handler to save this configuration on the entity.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 *
 * @see oe_link_lists_dynamic_form_link_list_dynamic_link_list_add_form_alter()
 * @see oe_link_lists_dynamic_form_link_list_dynamic_link_list_edit_form_alter()
 */
function oe_link_lists_dynamic_apply_link_list_form_alterations(array &$form, FormStateInterface $form_state) {
  // Alter the form itself.
  $form_builder = \Drupal::service('oe_link_lists_dynamic.entity_form_builder');
  $form_builder->buildForm($form, $form_state);

  // Apply the submit callback.
  $form['actions']['submit']['#submit'] = array_merge([[$form_builder, 'submitForm']], $form['actions']['submit']['#submit']);
}
